---
title: "Publication Ready Tables in R"
---

Are you tired of spending your time manually formatting tables for article submission? Does the idea of pasting regression coefficients from R to Excel make you wince? This session will demo how to make publication-quality (and reproducible!) data tables in R. We'll use the `gt` package to showcase options for table customization and the `gtsummary` package for ways to combine model outputs with table creation. 

Note that this session assumes a working knowledge of R; we will dive straight into main table content without a general overview of R.

**Workshop time**: 2/11/2026, 2:00-3:00pm

**Workshop registration**: https://ucsd.zoom.us/meeting/register/U2EwnvgUQiGL9VkivKWK-Q#/registration

**Instructors**: Stephanie Labou & Julien Brun


---

### About the data

The dataset used for this workshop is from the Journal article _"Seasonal changes in plankton food web structure and carbon dioxide flux from Southern California reservoirs"_ by and Adamczyk & Shurin (2015)
 <https://doi.org/10.1371/journal.pone.0140464>

The dataset used has been downloaded from Dryad: <https://doi.org/10.5061/dryad.6tn4h>

#### Attribute level metadata

The columns in this data file are the variables measured. The rows are the lakes (Poway, Murray, Miramar) and dates sampled.

Variables measured and their units:

- `julian_date` = year number followed by day number. (For example, 13177 is the 177th day of 2013)
- `sampling_date` = number of sampling days
- `h2o_temp_c` = water temperature (degrees celsius) 
- `air_temp_c` = air temperature (degrees celsius)
- `wind_speed_kph` = wind speed (kilometers per hour)
- `ph` = pH
- `total_alkalinity_ppm` = total alkalinity (parts per million)
- `chlorophyll_a_ugL` = chlorophyll-a (micrograms per liter)
- `salinity_ppt` = salinity (parts per thousand)
- `pco2_water_ppm` = partial pressure of carbon dioxide in the water (parts per million)
- `bacteria_number_per_L` = bateria abundance (number per liter)
- `total_nitrogen_mgL` = total nitrogen (milligrams per liter)
- `total_phosphorus_mgL` = total phosphorus (milligrams per liter)
- `dissolved_organic_carbon_mgL` = dissolved organic carbon (milligrams per liter)
- `particulate_organic_nitrogen_mgL` = particulate organic nitrogen (milligrams per liter)
- `particulate_organic_carbon_mgL` = particulate organic carbon (milligrams per liter)
- `co2_flux_mmol_m_day` = carbon dioxide flux (millimoles per square meter (m-2) per day (day-1))
- `pco2_atmosphere_ppm` = partial pressure of carbon dioxide in the atmosphere (parts per million)
- `zooplankton_community_avg_legnth_mm` = mean length of zooplankton community sampled (millimeters)
- `zooplankton_community_biomass_mgL` = biomass of zooplankton community sampled (milligrams per liter)

